### ISSUE TITLE
Variations of the MIPS Instruction-Set

### ISSUE THREAD

**Issue by contradictioned** [contradictioned/mips-syntax#7]
Hey,

I have seen now 2 pull requests that include "non-standard" instructions, whatever this means. I personally think, that it would not be good to suggest the existence of these instructions for everyone, so I am hesitating to merge these.

But on the other hand, I don't want to block people who use simulators/environements with more (pseudo-)instructions available. So how to proceed? I could imagine two ways:
1. There is one "pure" and one "rich" version of the syntax and you can choose in sublime which to use. The rich version has all (pseudo-)instructions available.
2. There is the pure version and one syntax to choose from per simulator (spim, mars, ...).

Any thoughts on this?

**Comment by adiaz101** [comment]
No thoughts on this but have a question about this syntax highlighting for MIPS. I installed this package already but how do I get it to work? Im saving my files as .asm and I assume that the package will start working here, but no results. Sorry if this is basic question but Im fairly new to sublime.

**Comment by contradictioned** [comment]
Hi,

how did you install it? Via [PackageControl](https://packagecontrol.io/) or manually?

And what Language is detected by sublime? This is displayed in the lower right corner of the sublime window. Normally `.asm` and `.s` file extensions should be recognized as MIPS.

**Comment by adiaz101** [comment]
I installed it via package control. Ok, I see it now. Thank you so much for this package, it is incredibly helpful

**Comment by contradictioned** [comment]
Ok, no variants.
